export const images = {
  // backgroundImage: require("../assets/background-image.png"),
  // bgImage: require("../assets/bg-image.png"),
  // iconForeground: require("../assets/icon-foreground.png"),
  // icon: require("../assets/icon.png"),
  // locationIcon: require("../assets/location-icon.png"),
  // loginBackgroundPage: require("../assets/login-background-page.png"),
  // logo: require("../assets/logo.png"),
  // mopedLocation: require("../assets/moped-location.png"),
  // navigateIcon: require("../assets/navigate-icon.png"),
  // padlockImage: require("../assets/padlock-image.png"),
  // speakerIcon: require("../assets/speaker-icon.png"),
  // splash: require("../assets/splash.png"),
  // volumeIcon: require("../assets/volume-icon.png"),
  // zebraNow: require("../assets/zebra-now.png"),
  // zebraNowSm: require("../assets/sm-zebra-now.png"),
  // myLocationIcon: require("../assets/myLocationIcon.png"),
  // red: require("../assets/red.png"),
  // green01: require("../assets/green_01.png"),
  // green03: require("../assets/green_03.png"),
  // yellow01: require("../assets/yellow_01.png"),
  // yellow: require("../assets/yellow.png"),
  // grey: require("../assets/grey.png"),
  // zebraCoordinatesLogo: require("../assets/zebra-coordinates-logo.png"),
  // tryZebraUnlimited: require("../assets/try-zebra-unlimited.png"),
  // mopedBattery75: require("../assets/moped-battery-75.png"),
  // subscribeBackgroundImage: require("../assets/subscription-background-image.png"),
  // confirmSubscriptionBackgroundImage: require("../assets/confirm-subscription-background-image.png"),
}

export default images
